name: Update book sqlite db

#on: push
on:
  schedule:
    - cron: '0 5 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Download
      run: ./.github/scripts/download_gutenberg_catalog.sh
      shell: bash

    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'books.db'

        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'Update book sqlite table'

        # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
        # - ignore -> errors will be logged but the step won't fail
        # - exitImmediately -> the action will stop right away, and the step will fail
        # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
        # Default: ignore
        pathspec_error_handling: exitImmediately

        # Arguments for the git pull command. By default, the action does not pull.
        # Default: ''
        pull: '--rebase --autostash ...'
        
