name: Update book sqlite db

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |- 
        echo Downloading catalog CSV
        curl https://www.gutenberg.org/cache/epub/feeds/pg_catalog.csv --output pg_catalog.csv
        
        echo Creating sqlite db
        sqlite3 book.sqlite3.temp ".mode csv" ".import pg_catalog.csv temp" ".exit"
        
        echo deleting junk rows
        sqlite3 book.sqlite3.temp 'DELETE FROM temp WHERE title = "No title";' ".exit"
        
        echo creating fts table
        sqlite3 book.sqlite3.temp "CREATE VIRTUAL TABLE books USING fts5('Text#',Type,Issued,Title,Language,Authors,Subjects,LoCC,Bookshelves);" ".exit"
        
        echo copying data to fts table
        sqlite3 book.sqlite3.temp "insert into books select * from temp;" ".exit"
        
        echo drop temp table 
        sqlite3 book.sqlite3.temp "drop table temp;" ".exit"
        
        echo verifying that db was created successfully
        sqlite3 book.sqlite3.temp "select * from books limit 10;" ".exit"
        [ $? -eq 0 ] || exit 1 
        rm -f book.sqlite
        mv book.sqlite3.temp book.sqlite3
        rm pg_catalog.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
