# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: update_book_sqlitedb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'src'

        # The local path to the directory where your repository is located. You should use actions/checkout first to set it up.
        # Default: '.'
#         cwd: './path/to/the/repo'

        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'updating book sqlite table'

        # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
        # - ignore -> errors will be logged but the step won't fail
        # - exitImmediately -> the action will stop right away, and the step will fail
        # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
        # Default: ignore
        pathspec_error_handling: exitImmediately

        # Arguments for the git pull command. By default, the action does not pull.
        # Default: ''
        pull: '--rebase --autostash ...'
        
