name: Update book sqlite db

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '*/2 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |- 
        echo Downloading catalog CSV
        curl https://www.gutenberg.org/cache/epub/feeds/pg_catalog.csv --output pg_catalog.csv
        echo Creating sqlite db
        sqlite3 book.sqlite3 ".mode csv" ".import pg_catalog.csv books" ".exit"
        echo verifying that db was created successfully
        sqlite3 book.sqlite3 "select * from books limit 10;" ".exit"
        [ $? -eq 0 ] || exit 1 
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
